/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.contabilidadmetales.contabilidadmetales.vistas;

import PlaceHolder.PlaceHolder;
import com.contabilidadmetales.contabilidadmetales.controlador.TipoMovimientoController;
import com.contabilidadmetales.contabilidadmetales.modelo.TipoMovimiento;
import java.awt.HeadlessException;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author narut
 */
public class FTipoMovimiento extends javax.swing.JFrame {

    /**
     * Creates new form FormularioTipoMovimiento
     */
    public FTipoMovimiento() {
        initComponents();
         this.setLocationRelativeTo(this);//para q se ponga en el centro
        this.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
           int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;//consigo el ancho y alto de la pantalla

    
           
        AsignacionPlaceHolder_Jtext();
        AsignacionImagenes();
    }
    
     public void AsignacionPlaceHolder_Jtext(){
     PlaceHolder placeholder = new PlaceHolder("Ingrese su descripción", DescripcionTx);//aqui le asigon l oq se vera en el text q se borra al escribir

    
    }
    
     public void AsignacionImagenes(){
    ImageIcon icon = new ImageIcon("Imagenes/FTipoMovimiento/Guardar.png");
jMenuGuardar.setIcon(icon);

     icon = new ImageIcon("Imagenes/FTipoMovimiento/Guardar2.png");
jMenuGuardar.setRolloverIcon(icon);

   icon = new ImageIcon("Imagenes/FTipoMovimiento/Cancelar.png");
jMenuCancelar.setIcon(icon);

icon = new ImageIcon("Imagenes/FTipoMovimiento/favicon.png");
jLabelIcono.setIcon(icon);

    }
    
    Boolean Actualizar = false;

    public FTipoMovimiento(JTextField DescripcionTx, JComboBox<String> TipoMovimiento) throws HeadlessException {
        this.DescripcionTx = DescripcionTx;
        this.TipoMovimiento = TipoMovimiento;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TipoMovimiento = new javax.swing.JComboBox<>();
        DescripcionTx = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabelIcono = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuGuardar = new javax.swing.JMenu();
        jMenuCancelar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setText("DESCRIPCIÓN");

        TipoMovimiento.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        TipoMovimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingreso", "Egreso" }));
        TipoMovimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        DescripcionTx.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        DescripcionTx.setBorder(null);
        DescripcionTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescripcionTxActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setText("OPCIÓN DE MOVIMIENTO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabelIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(DescripcionTx, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(jLabel2)
                    .addComponent(TipoMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)))
                .addGap(6, 6, 6)
                .addComponent(DescripcionTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(TipoMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenuGuardar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenuGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuGuardar.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuGuardarMenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenuGuardar);

        jMenuCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuCancelar.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuCancelarMenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenuCancelar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuGuardarMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuGuardarMenuSelected
     // TODO add your handling code here:
        String descripcion = DescripcionTx.getText();
        Boolean is = null;
        switch (TipoMovimiento.getSelectedItem().toString()) {
            case "Ingreso":
                is = true;
                break;
            case "Egreso":
                is = false;
                break;
            default:
                throw new AssertionError();
        }
        TipoMovimiento movimi = new TipoMovimiento(descripcion, is);
        TipoMovimientoController nuev = new TipoMovimientoController();
        nuev.agregarTipoMovimiento(movimi);
        this.dispose();     
    }//GEN-LAST:event_jMenuGuardarMenuSelected

    private void jMenuCancelarMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuCancelarMenuSelected
      this.dispose();
    }//GEN-LAST:event_jMenuCancelarMenuSelected

    private void DescripcionTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescripcionTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionTxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DescripcionTx;
    private javax.swing.JComboBox<String> TipoMovimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabelIcono;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCancelar;
    private javax.swing.JMenu jMenuGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
