/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.contabilidadmetales.contabilidadmetales.vistas;

import com.contabilidadmetales.contabilidadmetales.controlador.CPersona;
import com.contabilidadmetales.contabilidadmetales.controlador.Materiales;
import com.contabilidadmetales.contabilidadmetales.modelo.Material;
import com.contabilidadmetales.contabilidadmetales.modelo.persona;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author narut
 */
public class RegistrarProveedor extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarProveedor
     */
    private JTable table;
    int TipoDePersona;
    Materiales materiales;

    public RegistrarProveedor(JTable table) {
        initComponents();
        this.table = table;
        LContraseña.setVisible(false);
        Contraseña.setVisible(false);
        materiales = new Materiales();
        listarMaterialesConValor();
    }

    public void listarMaterialesConValor() {
        ListaDePresiosTA.setText("");
        for (Material material : materiales.listarMateriales()) {
            ListaDePresiosTA.append( material.getNombre() + "," + material.getValor() + "\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NombreTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TipoIdentificacionTF = new javax.swing.JComboBox<>();
        IdentificacionTF = new javax.swing.JTextField();
        CelularTF = new javax.swing.JTextField();
        BotonResitrar = new javax.swing.JButton();
        BotonResitrar1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaDePresiosTA = new javax.swing.JTextArea();
        MaterialTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ValorTF = new javax.swing.JTextField();
        BotonResitrar2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DescripcionTA = new javax.swing.JTextArea();
        TipoComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        LContraseña = new javax.swing.JLabel();
        Contraseña = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        setForeground(java.awt.Color.white);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel1.setText("Registro");

        jLabel2.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel2.setText("nombre completo");

        NombreTF.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel4.setText("identificacion");

        jLabel3.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel3.setText("Celular");

        jLabel5.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel5.setText("Tipo Documento");

        TipoIdentificacionTF.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        TipoIdentificacionTF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cc" }));

        IdentificacionTF.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N

        CelularTF.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N

        BotonResitrar.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        BotonResitrar.setText("Registrar");
        BotonResitrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonResitrarActionPerformed(evt);
            }
        });

        BotonResitrar1.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        BotonResitrar1.setText("Cancelar");
        BotonResitrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonResitrar1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel6.setText("Lista de presios");

        ListaDePresiosTA.setEditable(false);
        ListaDePresiosTA.setColumns(20);
        ListaDePresiosTA.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        ListaDePresiosTA.setRows(5);
        jScrollPane1.setViewportView(ListaDePresiosTA);

        MaterialTF.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel7.setText("Material");

        jLabel8.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel8.setText("Valor");

        ValorTF.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N

        BotonResitrar2.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        BotonResitrar2.setText("Registrar a la lista");
        BotonResitrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonResitrar2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel9.setText("Descripcion");

        DescripcionTA.setColumns(20);
        DescripcionTA.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        DescripcionTA.setRows(5);
        jScrollPane2.setViewportView(DescripcionTA);

        TipoComboBox.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        TipoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proveedor", "Cliente", "Usuario" }));
        TipoComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TipoComboBoxMouseClicked(evt);
            }
        });
        TipoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoComboBoxActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel10.setText("Tipo de persona ");

        LContraseña.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        LContraseña.setText("Contraseña");

        Contraseña.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(TipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MaterialTF, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ValorTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonResitrar2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(231, 231, 231)
                                .addComponent(BotonResitrar)
                                .addGap(38, 38, 38)
                                .addComponent(BotonResitrar1))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel9))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(TipoIdentificacionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane2)
                                        .addComponent(jScrollPane1)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(210, 210, 210)
                                                .addComponent(CelularTF, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(324, 324, 324)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(LContraseña)
                                                    .addComponent(jLabel4))))
                                        .addGap(62, 62, 62)
                                        .addComponent(IdentificacionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(404, 404, 404)
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(NombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 23, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CelularTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(IdentificacionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoIdentificacionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(LContraseña)
                    .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(278, 278, 278))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonResitrar2)
                            .addComponent(ValorTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaterialTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonResitrar)
                            .addComponent(BotonResitrar1))
                        .addContainerGap(18, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private persona nuevoPro;

    public persona getNuevoPro() {
        return nuevoPro;
    }

    public void setNuevoPro(persona nuevoPro) {
        this.nuevoPro = nuevoPro;
    }

    public void tabla() {
        String[] pro = new String[5];
        pro[0] = nuevoPro.getNombre();
        pro[1] = nuevoPro.getCelular();
        pro[2] = nuevoPro.getIdentificacion();
        pro[3] = nuevoPro.getTipoDocumento_nombre();
        pro[4] = nuevoPro.getDescripcion();
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.addRow(pro);
    }


    private void BotonResitrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonResitrarActionPerformed
        switch (TipoComboBox.getSelectedItem().toString()) {
            case "Cliente":
                TipoDePersona = 2;
                break;
            case "Proveedor":
                TipoDePersona = 1;
                break;
            case "Usuario":
                TipoDePersona = 3;
                break;
            default:
                throw new AssertionError();
        }
        String nombre, Celular, identificacion, TipoDocumento;
        nombre = NombreTF.getText();
        Celular = CelularTF.getText();
        identificacion = IdentificacionTF.getText();
        TipoDocumento = (String) TipoIdentificacionTF.getSelectedItem();
        nuevoPro = new persona(nombre, Celular, identificacion, TipoDocumento, ListaDePresiosTA.getText(), DescripcionTA.getText());
        this.setNuevoPro(nuevoPro);
        CPersona Proveedor = new CPersona();
        Proveedor.registrarProvedor(nuevoPro, TipoDePersona, Contraseña.getText());
        this.dispose();
        tabla();

    }//GEN-LAST:event_BotonResitrarActionPerformed

    private void BotonResitrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonResitrar1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BotonResitrar1ActionPerformed

    private void BotonResitrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonResitrar2ActionPerformed
        // TODO add your handling code here:
        String nombreMaterial = MaterialTF.getText().trim();

        double nuevoValor = Double.parseDouble(ValorTF.getText());

        // Buscamos el material en la tabla
        Material material = materiales.obtenerMaterialPorNombre(nombreMaterial);

        if (material != null) {
            // Si el material existe, comparamos su valor actual con el nuevo valor
            if (material.getValor() != nuevoValor) {
                // Si el valor es distinto, actualizamos el registro en la tabla
                material.setValor(nuevoValor);
                if (materiales.actualizarMaterial(material)) {
                    JOptionPane.showConfirmDialog(null, "Material actualizado correctamente");
                    listarMaterialesConValor();
                } else {
                    JOptionPane.showConfirmDialog(null, "Error al actualizar el material");
                }
            } else {
                // Si el valor es el mismo, no hacemos nada
                JOptionPane.showConfirmDialog(null, "El material ya tiene ese valor");
            }
        } else {
            // Si el material no existe, lo insertamos en la tabla
            Material nuevoMaterial = new Material();
            nuevoMaterial.setNombre(nombreMaterial);
            nuevoMaterial.setValor(nuevoValor);
            if (materiales.insertarMaterial(nuevoMaterial)) {
               // JOptionPane.showConfirmDialog(null, "Material insertado correctamente");
                listarMaterialesConValor();
            } else {
                JOptionPane.showConfirmDialog(null, "Error al insertar el material");
            }
        }
    }//GEN-LAST:event_BotonResitrar2ActionPerformed

    private void TipoComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TipoComboBoxMouseClicked
        // TODO add your handling code her

    }//GEN-LAST:event_TipoComboBoxMouseClicked

    private void TipoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoComboBoxActionPerformed
        // TODO add your handling code here:
        if (TipoComboBox.getSelectedItem().toString().equals("Usuario")) {
            LContraseña.setVisible(true);
            Contraseña.setVisible(true);
            LContraseña.repaint();
        } else {
            LContraseña.setVisible(false);
            Contraseña.setVisible(false);
        }
    }//GEN-LAST:event_TipoComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonResitrar;
    private javax.swing.JButton BotonResitrar1;
    private javax.swing.JButton BotonResitrar2;
    private javax.swing.JTextField CelularTF;
    private javax.swing.JTextField Contraseña;
    private javax.swing.JTextArea DescripcionTA;
    private javax.swing.JTextField IdentificacionTF;
    private javax.swing.JLabel LContraseña;
    private javax.swing.JTextArea ListaDePresiosTA;
    private javax.swing.JTextField MaterialTF;
    private javax.swing.JTextField NombreTF;
    private javax.swing.JComboBox<String> TipoComboBox;
    private javax.swing.JComboBox<String> TipoIdentificacionTF;
    private javax.swing.JTextField ValorTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
